-- AlterTable
ALTER TABLE `user` ADD COLUMN `city` VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN `country` VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN `postCode` VARCHAR(50) NOT NULL DEFAULT '',
    MODIFY `address` VARCHAR(50) NOT NULL DEFAULT '';
